// Code generated by goplus from git.gp. DO NOT EDIT.
//goplus:v v0.28.0

// Package git provides an integration with the git command
package git

import (
	"context"
	"errors"
	"strings"

	"github.com/caarlos0/log"
	process "goforge.dev/goplus/std/process"
)

// IsRepo returns true if current folder is a git repository.
func IsRepo(ctx context.Context) bool {
	out, err := Run(ctx, "rev-parse", "--is-inside-work-tree")
	return err == nil && strings.TrimSpace(out) == "true"
}

func RunWithEnv(ctx context.Context, env []string, args ...string) (string, error) {
	extraArgs := []string{
		"-c", "log.showSignature=false",
	}
	args = append(extraArgs, args...)
	// git execution runs through std/process. When a caller supplies an
	// environment, git historically runs with exactly that (no inheritance),
	// which maps to a clean-env process capability.
	spec := process.Spec{Path: "git", Args: args}
	if len(env) > 0 {
		spec.Env, spec.Clean = env, true
	}
	out, err := process.Run(ctx, spec)

	log.WithField("args", args).
		WithField("stdout", strings.TrimSpace(string(out.Stdout))).
		WithField("stderr", strings.TrimSpace(string(out.Stderr))).
		Debug("git command result")

	if err != nil {
		return "", errors.New(string(out.Stderr))
	}

	return string(out.Stdout), nil
}

// Run runs a git command and returns its output or errors.
func Run(ctx context.Context, args ...string) (string, error) {
	return RunWithEnv(ctx, []string{}, args...)
}

// Clean the output.
func Clean(output string, err error) (string, error) {
	output = strings.ReplaceAll(strings.Split(output, "\n")[0], "'", "")
	if err != nil {
		err = errors.New(strings.TrimSuffix(err.Error(), "\n"))
	}
	return output, err
}

// CleanAllLines returns all the non empty lines of the output, cleaned up.
func CleanAllLines(output string, err error) ([]string, error) {
	var result []string
	for line := range strings.SplitSeq(output, "\n") {
		l := strings.TrimSpace(strings.ReplaceAll(line, "'", ""))
		if l == "" {
			continue
		}
		result = append(result, l)
	}
	// TODO: maybe check for exec.ExitError only?
	if err != nil {
		err = errors.New(strings.TrimSuffix(err.Error(), "\n"))
	}
	return result, err
}
