// Code generated by goplus from doc.gp. DO NOT EDIT.
//goplus:v v0.28.0

// Package gomod provides go modules utilities, such as template variables and the ability to proxy the module from
// proxy.golang.org.
package gomod
