// Code generated by goplus from doc.gp. DO NOT EDIT.
//goplus:v v0.28.0

// Package blob provides the pipe implementation that uploads files to "blob" providers, such as s3, gcs and azure.
package blob
