// Code generated by goplus from endpoint.gp. DO NOT EDIT.
//goplus:v v0.28.0

package discourse

type postsRequest struct {
	Title    string `json:"title"`
	Raw      string `json:"raw"`
	Category int    `json:"category"`
}
