// Code generated by goplus from doc.gp. DO NOT EDIT.
//goplus:v v0.28.0

// Package brew implements the Pipe, providing formula generation and
// uploading it to a configured repo.
//
// Deprecated: use the [cask] package instead.
package brew
