// Code generated by goplus from middleware.gp. DO NOT EDIT.
//goplus:v v0.28.0

// Package middleware define middlewares for Actions.
package middleware

import "goforge.dev/gpreleaser/pkg/context"

// Action is a function that takes a context and returns an error.
// It is used on Pipers, Defaulters and Publishers, although they are not
// aware of this generalization.
type Action func(ctx *context.Context) error
