// Code generated by goplus from go.gp. DO NOT EDIT.
//goplus:v v0.28.0

package testlib

import (
	"runtime"
	"strings"
)

// GoVersion is the current Go version, without the "go" prefix.
var GoVersion = strings.TrimPrefix(runtime.Version(), "go")
