// Code generated by goplus from skip.gp. DO NOT EDIT.
//goplus:v v0.28.0

package testlib

import (
	"testing"

	"github.com/stretchr/testify/require"
	"goforge.dev/gpreleaser/internal/pipe"
)

// AssertSkipped asserts that a pipe was skipped.
func AssertSkipped(t *testing.T, err error) {
	t.Helper()
	require.ErrorAs(t, err, &pipe.ErrSkip{}, "expected a pipe.ErrSkip but got %v", err)
}
